[package]
name = "annotate-snippets"
version = "0.1.0"
authors = ["Zibi Braniecki <zibi@braniecki.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = { version = "0.12", optional = true }
termcolor = { version = "1", optional = true }

[dev-dependencies]
criterion = "0.3"

[features]
default = []
color = ["ansi_term"]
color2 = ["termcolor"]
unicode = []

[[bench]]
name = "simple"
harness = false
