[package]
name = "annotate-snippets"
version = "0.1.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]

[dependencies]

[dev-dependencies]
glob = "0.2"
serde_yaml = "0.7"
serde = "1.0"
serde_derive = "1.0"
difference = "2.0"
ansi_term = "0.11"
